from PIL import Image
import sys
import os

def remove_black_background(input_path, output_path):
    try:
        print(f"Opening {input_path}")
        img = Image.open(input_path)
        img = img.convert("RGBA")
        datas = img.getdata()

        newData = []
        for item in datas:
            # If pixel is very dark (black background), make it transparent
            # Threshold 20 is safe for solid black backgrounds generated by AI
            if item[0] < 20 and item[1] < 20 and item[2] < 20:
                newData.append((255, 255, 255, 0)) # Transparent
            else:
                newData.append(item)

        img.putdata(newData)
        img.save(output_path, "PNG")
        print(f"Successfully saved to {output_path}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    input_file = "/home/majdi/projet/src/assets/images/spongebob_fixed.png"
    # Save to the same location
    remove_black_background(input_file, input_file)
